// Get all cards' information
get http://localhost:5126/api/cards

###
// Get one card by Id
get http://localhost:5126/api/cards/1234000022340000

###
// Add a card
post http://localhost:5126/api/cards/add
Content-Type: application/json

{
    "creditNumber": "1234000022340000",
    "cvc": "013",
    "expiryDateMonth": "1",
    "expiryDateDay": "2"
}
