// Get all cards' information
get http://localhost:5126/api/cards

###
// Get one card by Card Number
get http://localhost:5126/api/cards/1234000022340000

###
// Add a card
post http://localhost:5126/api/cards/add
Content-Type: application/json

{
    "name": "Tom",
    "creditNumber": "1234000322340003",
    "cvc": "013",
    "expiryDateYear": "23",
    "expiryDateMonth": "11"
}
